## Overview
This script aims to preprocess the excel spreadsheet of Motor Imagery, Thermal, Electrical, and Finger Tapping data. Then, it uses categorizes these data into the following groups for the Applied Machine Learning aspect.
- Motor: Motor Imagery & Finger Tapping Data
- Sesnory: Thermal & Electrical Data

#### Part 1 - Data Input & Processing

In [70]:
# Import required libraries
import pandas as pd 
import numpy as np

In [71]:
# Read in each individual sheet in the excel spreadsheet
fNIRS_tstats = pd.read_excel('../data/ds005776.xlsx', sheet_name="tstats")
fNIRS_bstats = pd.read_excel('../data/ds005776.xlsx', sheet_name="bstats")

In [72]:
# Fill all missing NA cells with a scalar value of 0
fNIRS_tstats = fNIRS_tstats.fillna(0)
fNIRS_bstats = fNIRS_bstats.fillna(0)

In [73]:
# Create a new 'Type' column and condition its value on the data type
fNIRS_tstats['Type'] = np.where(
    (fNIRS_tstats['Cond'] == 'FingerTapping') | (fNIRS_tstats['Cond'] == 'MotorImagery'),
    'Motor',
    'Sensory'
)

fNIRS_bstats['Type'] = np.where(
    (fNIRS_bstats['Cond'] == 'FingerTapping') | (fNIRS_bstats['Cond'] == 'MotorImagery'),
    'Motor',
    'Sensory'
)

# Remove the sub- prefix from the front of each Subject
fNIRS_tstats['Subject'] = fNIRS_tstats['Subject'].str.replace('sub-', '', regex=False)
fNIRS_bstats['Subject'] = fNIRS_bstats['Subject'].str.replace('sub-', '', regex=False)

In [74]:

# Create a new 'Trial' column and make its value the second part of Cond_extended
#fNIRS_tstats['Trial'] = fNIRS_tstats['Cond_extended'].str.extract(r'trial[_]?(\d+)').astype(int)
#fNIRS_bstats['Trial'] = fNIRS_bstats['Cond_extended'].str.extract(r'trial[_]?(\d+)').astype(int)

# Create Temp
#t_trial = fNIRS_tstats.pop('Trial')
#b_trial = fNIRS_bstats.pop('Trial')

# Move it as the 2nd Column
#fNIRS_tstats.insert(3, "Trial", t_trial)
#fNIRS_bstats.insert(3, "Trial", b_trial)

In [75]:
# Set the index of the dataframes to be by 'Type'
fNIRS_tstats.set_index('Type', inplace=True)
fNIRS_bstats.set_index('Type', inplace=True)

In [76]:
# Drop all the unneeded columns
fNIRS_tstats = fNIRS_tstats.drop(columns=["Cond_extended", "Cond", "Session", "FileNumber"], errors='ignore')
fNIRS_bstats = fNIRS_bstats.drop(columns=["Cond_extended", "Cond", "Session", "FileNumber"], errors='ignore')

# Verify columns are correct
print(fNIRS_tstats.columns.tolist())

['Subject', 'S1_D1_hbo', 'S1_D1_hbr', 'S2_D1_hbo', 'S2_D1_hbr', 'S2_D2_hbo', 'S2_D2_hbr', 'S3_D1_hbo', 'S3_D1_hbr', 'S3_D3_hbo', 'S3_D3_hbr', 'S4_D1_hbo', 'S4_D1_hbr', 'S4_D2_hbo', 'S4_D2_hbr', 'S4_D3_hbo', 'S4_D3_hbr', 'S4_D4_hbo', 'S4_D4_hbr', 'S5_D3_hbo', 'S5_D3_hbr', 'S5_D5_hbo', 'S5_D5_hbr', 'S6_D3_hbo', 'S6_D3_hbr', 'S6_D4_hbo', 'S6_D4_hbr', 'S6_D5_hbo', 'S6_D5_hbr', 'S6_D6_hbo', 'S6_D6_hbr', 'S7_D7_hbo', 'S7_D7_hbr', 'S7_D9_hbo', 'S7_D9_hbr', 'S8_D7_hbo', 'S8_D7_hbr', 'S8_D8_hbo', 'S8_D8_hbr', 'S8_D9_hbo', 'S8_D9_hbr', 'S8_D10_hbo', 'S8_D10_hbr', 'S9_D9_hbo', 'S9_D9_hbr', 'S9_D11_hbo', 'S9_D11_hbr', 'S10_D9_hbo', 'S10_D9_hbr', 'S10_D10_hbo', 'S10_D10_hbr', 'S10_D11_hbo', 'S10_D11_hbr', 'S10_D12_hbo', 'S10_D12_hbr', 'S11_D11_hbo', 'S11_D11_hbr', 'S12_D11_hbo', 'S12_D11_hbr', 'S12_D12_hbo', 'S12_D12_hbr', 'S13_D13_hbo', 'S13_D13_hbr', 'S13_D14_hbo', 'S13_D14_hbr', 'S14_D14_hbo', 'S14_D14_hbr', 'S14_D15_hbo', 'S14_D15_hbr', 'S15_D15_hbo', 'S15_D15_hbr', 'S15_D16_hbo', 'S15_D16_hbr']

In [77]:
# Confirm that the dataframe structure is correct
fNIRS_tstats

,Subject,S1_D1_hbo,S1_D1_hbr,S2_D1_hbo,S2_D1_hbr,S2_D2_hbo,S2_D2_hbr,S3_D1_hbo,S3_D1_hbr,S3_D3_hbo,...,S13_D14_hbo,S13_D14_hbr,S14_D14_hbo,S14_D14_hbr,S14_D15_hbo,S14_D15_hbr,S15_D15_hbo,S15_D15_hbr,S15_D16_hbo,S15_D16_hbr
Type,,,,,,,,,,,,,,,,,,,,,
Sensory,356,0.493721,-0.766741,0.567587,-1.344679,0.429223,0.232113,0.844482,-0.737692,-0.433094,...,-1.123564,0.960432,-2.231504,2.985463,1.824350,-1.653149,1.212201,-0.239501,0.489141,-1.436809
Sensory,356,-0.569585,-1.098043,0.066414,-1.274389,-0.386449,0.654922,-1.649411,1.723693,-1.610510,...,1.775918,1.669018,-1.133517,3.286378,4.866750,3.627134,2.090548,1.523373,-1.507405,1.479719
Sensory,356,0.859753,-0.805235,1.259660,-1.430440,-0.486831,0.121435,1.214200,-0.542301,0.417734,...,-1.589901,1.376176,-0.343042,3.706916,-0.760749,6.070341,-1.456933,0.953300,1.466210,-0.427621
Sensory,356,-0.718349,0.869606,1.308947,0.363870,1.018017,0.013534,0.284458,-0.355039,0.044605,...,-0.837509,0.803487,-1.247155,1.384094,-1.835050,-0.345099,-0.343674,-0.293559,-2.654850,-1.836174
Sensory,356,0.497515,-0.512224,1.696572,0.011593,2.156910,-0.187797,1.163204,-0.659332,1.671221,...,0.602692,0.141459,-0.442834,1.197451,1.545431,-0.721900,0.851430,-0.508601,-0.453208,-1.154429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Motor,380,2.215452,-1.474318,1.214648,0.463128,-0.023419,-0.348024,0.298632,-0.904994,1.532925,...,2.571758,0.121635,1.902192,0.271464,2.345531,0.188680,1.281041,0.859593,2.507403,0.656876
Motor,380,-0.777072,0.072229,-0.130087,0.557504,0.518854,0.100366,-0.576661,0.388357,0.096752,...,0.120059,-0.605880,-0.391222,-0.170211,-0.627139,-0.227051,-0.908082,0.625950,-0.908356,0.468572
Motor,380,2.752689,-0.643925,0.263145,-0.368293,-0.199564,1.372369,1.958705,-1.088672,4.660410,...,-0.346303,-0.979193,-0.095099,-0.141790,1.073829,-0.106442,-0.543484,0.129753,0.933121,0.071683
Motor,380,0.673214,0.720687,0.524223,-0.310116,1.226013,-0.792821,0.884440,-2.277066,0.434985,...,0.545453,-0.475096,-1.092386,0.075800,-0.408090,0.425919,0.218474,0.777740,-0.420050,-0.016820
Motor,380,-0.088826,-0.066400,-0.464304,0.442351,1.653154,-1.713849,-0.133731,0.222247,0.156045,...,-1.642416,2.718983,-1.857037,-0.178736,-0.127316,-0.220009,-0.233622,1.399710,-0.087881,0.789441

In [78]:
# Save as Excel Spreadsheets
fNIRS_bstats.to_excel('../data/bstats.xlsx', index=True) # Un-Normalized Statistics
fNIRS_tstats.to_excel('../data/tstats.xlsx', index=True) # Normalized Statistics

In [79]:
# Convert to a numpy array
fNIRS_tstats_ndarray = fNIRS_tstats.to_numpy()
fNIRS_bstats_ndarray = fNIRS_bstats.to_numpy()

### Machine Learning Models
- This script takes in an N-Dimensional Array from NumPy and then trains ML Models using that data.
- The N-Dimensional arrays will be split into training/testing sets and fed into a ML model

#### Part 2 - Data Splitting

In [80]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.metrics import accuracy_score

In [81]:
X=fNIRS_bstats_ndarray[:,5::]
y=1*(fNIRS_tstats.index=='Motor')

# Split into training and testing sets, everything up to here is the same
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#### Part 3 - Model Training & Assessment

In [82]:
# Create and train the Linear model
#lin_model = SVC(kernel='linear', C=5) 
#lin_model.fit(X_train, y_train)

# Make predictions
#y_pred = lin_model.predict(X_test)

# Evaluate the model
#print("Accuracy:", accuracy_score(y_test, y_pred))

In [83]:
# Train an Polynomial Model
poly_model = SVC(kernel='poly', C=5) # Only line that needs to change
poly_model.fit(X_train, y_train)

# Make predictions
y_pred = poly_model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6435185185185185

In [84]:
# Train an RBF Model
rbf_model = SVC(kernel='rbf', C=5) # Only line that needs to change
rbf_model.fit(X_train, y_train)

# Make predictions
y_pred = rbf_model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6435185185185185

In [85]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Train an LDA Model
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

# Make predictions
y_pred = lda.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6944444444444444

#### Part 4a - Cross Validation (Naive)

In [86]:
# Perform 50-fold cross-validation on LDA Model
LDA_scores = cross_val_score(lda, X, y, cv=10, scoring='accuracy')

print("Cross-validation scores:", LDA_scores)
print("Mean accuracy:", LDA_scores.mean())

Cross-validation scores: [0.80555556 0.72222222 0.70833333 0.59722222 0.59722222 0.66666667
 0.76388889 0.64788732 0.6056338  0.70422535]
Mean accuracy: 0.681885758998435

In [87]:
# Perform 10-fold cross-validation on Linear Model
# Need to optimize - exponential runtime
#Linear_scores = cross_val_score(lin_model, X, y, cv=10, scoring='accuracy')

#print("Cross-validation scores:", Linear_scores)
#print("Mean accuracy:", Linear_scores.mean())

#### Part 4b - Cross Validation (Within Subjects)
- Trials are partitioned into two sets: Sensory and Motory - $Trials \in [Sensory, Motor]$
- For S in subjects, take $min(Sensory, Motor) \in S$. That will be the size of the data set for both
    - Sensory (N): 10% Hold Out, 90% Training, Motor (N with M - N ignored): 10% Hold Out, 90% Training
    
**No need to worry about same data point count among different subjects**

In [88]:
fNIRS_tstats

,Subject,S1_D1_hbo,S1_D1_hbr,S2_D1_hbo,S2_D1_hbr,S2_D2_hbo,S2_D2_hbr,S3_D1_hbo,S3_D1_hbr,S3_D3_hbo,...,S13_D14_hbo,S13_D14_hbr,S14_D14_hbo,S14_D14_hbr,S14_D15_hbo,S14_D15_hbr,S15_D15_hbo,S15_D15_hbr,S15_D16_hbo,S15_D16_hbr
Type,,,,,,,,,,,,,,,,,,,,,
Sensory,356,0.493721,-0.766741,0.567587,-1.344679,0.429223,0.232113,0.844482,-0.737692,-0.433094,...,-1.123564,0.960432,-2.231504,2.985463,1.824350,-1.653149,1.212201,-0.239501,0.489141,-1.436809
Sensory,356,-0.569585,-1.098043,0.066414,-1.274389,-0.386449,0.654922,-1.649411,1.723693,-1.610510,...,1.775918,1.669018,-1.133517,3.286378,4.866750,3.627134,2.090548,1.523373,-1.507405,1.479719
Sensory,356,0.859753,-0.805235,1.259660,-1.430440,-0.486831,0.121435,1.214200,-0.542301,0.417734,...,-1.589901,1.376176,-0.343042,3.706916,-0.760749,6.070341,-1.456933,0.953300,1.466210,-0.427621
Sensory,356,-0.718349,0.869606,1.308947,0.363870,1.018017,0.013534,0.284458,-0.355039,0.044605,...,-0.837509,0.803487,-1.247155,1.384094,-1.835050,-0.345099,-0.343674,-0.293559,-2.654850,-1.836174
Sensory,356,0.497515,-0.512224,1.696572,0.011593,2.156910,-0.187797,1.163204,-0.659332,1.671221,...,0.602692,0.141459,-0.442834,1.197451,1.545431,-0.721900,0.851430,-0.508601,-0.453208,-1.154429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Motor,380,2.215452,-1.474318,1.214648,0.463128,-0.023419,-0.348024,0.298632,-0.904994,1.532925,...,2.571758,0.121635,1.902192,0.271464,2.345531,0.188680,1.281041,0.859593,2.507403,0.656876
Motor,380,-0.777072,0.072229,-0.130087,0.557504,0.518854,0.100366,-0.576661,0.388357,0.096752,...,0.120059,-0.605880,-0.391222,-0.170211,-0.627139,-0.227051,-0.908082,0.625950,-0.908356,0.468572
Motor,380,2.752689,-0.643925,0.263145,-0.368293,-0.199564,1.372369,1.958705,-1.088672,4.660410,...,-0.346303,-0.979193,-0.095099,-0.141790,1.073829,-0.106442,-0.543484,0.129753,0.933121,0.071683
Motor,380,0.673214,0.720687,0.524223,-0.310116,1.226013,-0.792821,0.884440,-2.277066,0.434985,...,0.545453,-0.475096,-1.092386,0.075800,-0.408090,0.425919,0.218474,0.777740,-0.420050,-0.016820
Motor,380,-0.088826,-0.066400,-0.464304,0.442351,1.653154,-1.713849,-0.133731,0.222247,0.156045,...,-1.642416,2.718983,-1.857037,-0.178736,-0.127316,-0.220009,-0.233622,1.399710,-0.087881,0.789441

In [89]:
def cv_internal(model, data):
    # Group Data by the Type and Subject - Ignore Everything else

    # For each Subject, split Trials into Test/Hold Out sets & Set Fold to be Subjects 

    # Run ML Model on each Fold, assess performance per Subject
  
    # Take the average performance metric and return
    return None